name: Design Sync
description: Track a design alignment item.
title: "[design] "
labels: ["design"]
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
    validations:
      required: true
